"""
reports/pdf_generator.py

Executive Report Generator

Produces boardroom-ready PDF reports using ReportLab. The report structure
mirrors what a McKinsey or Accenture analyst would hand to a C-suite client:
executive summary → key findings → data visualizations → recommendations →
risk register.

The PDF is generated in-memory (BytesIO) so Streamlit can offer it as a
download without writing to disk.
"""

import io
import logging
from datetime import datetime
from typing import Optional

import pandas as pd
import numpy as np
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    Image,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import KeepTogether

logger = logging.getLogger(__name__)

# ── Brand colors (GCC-professional palette) ───────────────────────────────────
NAVY = colors.HexColor("#0A2342")
TEAL = colors.HexColor("#00A8A8")
LIGHT_GRAY = colors.HexColor("#F5F7FA")
MID_GRAY = colors.HexColor("#8A8A8A")
WHITE = colors.white
ALERT_RED = colors.HexColor("#C0392B")
ALERT_AMBER = colors.HexColor("#E67E22")
ALERT_GREEN = colors.HexColor("#27AE60")


def _header_footer(canvas, doc):
    """Page header and footer drawn on every page."""
    canvas.saveState()
    width, height = A4

    # Top bar
    canvas.setFillColor(NAVY)
    canvas.rect(0, height - 22 * mm, width, 22 * mm, fill=1, stroke=0)

    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(15 * mm, height - 13 * mm, "AUTONOMOUS BUSINESS INTELLIGENCE PLATFORM")

    canvas.setFont("Helvetica", 8)
    canvas.drawRightString(
        width - 15 * mm,
        height - 13 * mm,
        f"CONFIDENTIAL — {datetime.now().strftime('%d %B %Y')}",
    )

    # Footer line
    canvas.setStrokeColor(TEAL)
    canvas.setLineWidth(1)
    canvas.line(15 * mm, 12 * mm, width - 15 * mm, 12 * mm)

    canvas.setFillColor(MID_GRAY)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawString(15 * mm, 7 * mm, "Generated by Autonomous BI Platform — AI-Powered Enterprise Intelligence")
    canvas.drawRightString(width - 15 * mm, 7 * mm, f"Page {doc.page}")

    canvas.restoreState()


def build_styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "cover_title": ParagraphStyle(
            "cover_title",
            fontName="Helvetica-Bold",
            fontSize=28,
            textColor=NAVY,
            spaceAfter=8,
            alignment=TA_LEFT,
        ),
        "cover_subtitle": ParagraphStyle(
            "cover_subtitle",
            fontName="Helvetica",
            fontSize=13,
            textColor=MID_GRAY,
            spaceAfter=4,
            alignment=TA_LEFT,
        ),
        "section_heading": ParagraphStyle(
            "section_heading",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=NAVY,
            spaceBefore=14,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "body",
            fontName="Helvetica",
            fontSize=9.5,
            textColor=colors.HexColor("#2C2C2C"),
            leading=15,
            spaceAfter=6,
            alignment=TA_JUSTIFY,
        ),
        "highlight_box": ParagraphStyle(
            "highlight_box",
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=NAVY,
            leading=14,
            leftIndent=10,
        ),
        "small_label": ParagraphStyle(
            "small_label",
            fontName="Helvetica",
            fontSize=7.5,
            textColor=MID_GRAY,
            spaceAfter=2,
        ),
        "kpi_number": ParagraphStyle(
            "kpi_number",
            fontName="Helvetica-Bold",
            fontSize=22,
            textColor=TEAL,
            alignment=TA_CENTER,
        ),
        "kpi_label": ParagraphStyle(
            "kpi_label",
            fontName="Helvetica",
            fontSize=8,
            textColor=MID_GRAY,
            alignment=TA_CENTER,
        ),
        "alert": ParagraphStyle(
            "alert",
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=ALERT_RED,
            leading=14,
        ),
    }


class ExecutiveReportGenerator:
    """
    Generates structured PDF executive reports from pipeline results.
    Call generate() to get a BytesIO object ready for Streamlit download.
    """

    def __init__(self):
        self.styles = build_styles()

    def _make_kpi_table(self, kpis: list[dict]) -> Table:
        """Render a row of KPI tiles (metric name + value)."""
        headers = [Paragraph(k["label"], self.styles["kpi_label"]) for k in kpis]
        values = [Paragraph(k["value"], self.styles["kpi_number"]) for k in kpis]

        t = Table(
            [headers, values],
            colWidths=[A4[0] / len(kpis) - 15 * mm / len(kpis)] * len(kpis),
        )
        t.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_GRAY]),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D7E2")),
                ("INNERGRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D0D7E2")),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ])
        )
        return t

    def _df_to_table(self, df: pd.DataFrame, max_rows: int = 20) -> Table:
        """Convert a pandas DataFrame to a formatted ReportLab Table."""
        df_display = df.head(max_rows).copy()
        # Round floats
        for col in df_display.select_dtypes(include=[float]).columns:
            df_display[col] = df_display[col].round(2)

        headers = [
            Paragraph(str(c).replace("_", " ").title(), self.styles["small_label"])
            for c in df_display.columns
        ]
        rows = [headers]
        for _, row in df_display.iterrows():
            rows.append([
                Paragraph(str(v), self.styles["body"]) for v in row.values
            ])

        col_count = len(df_display.columns)
        usable_width = A4[0] - 30 * mm
        col_width = usable_width / col_count

        t = Table(rows, colWidths=[col_width] * col_count, repeatRows=1)
        t.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 8),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
                ("FONTSIZE", (0, 1), (-1, -1), 7.5),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D0D7E2")),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        return t

    def generate(
        self,
        title: str,
        user_question: str,
        headline: str,
        analysis: str,
        recommendations: str,
        df: Optional[pd.DataFrame] = None,
        anomalies: Optional[list] = None,
        sql_query: str = "",
        role: str = "executive",
        company_name: str = "Enterprise Client",
    ) -> io.BytesIO:
        """
        Build the full PDF report. Returns a BytesIO buffer.
        """
        buffer = io.BytesIO()

        doc = BaseDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=15 * mm,
            leftMargin=15 * mm,
            topMargin=28 * mm,
            bottomMargin=20 * mm,
        )

        frame = Frame(
            doc.leftMargin,
            doc.bottomMargin,
            doc.width,
            doc.height,
            id="main",
        )
        template = PageTemplate(id="main", frames=[frame], onPage=_header_footer)
        doc.addPageTemplates([template])

        story = []
        s = self.styles

        # ── Cover section ──────────────────────────────────────────────────
        story.append(Spacer(1, 1.5 * cm))
        story.append(Paragraph(company_name.upper(), s["cover_subtitle"]))
        story.append(Paragraph(title, s["cover_title"]))
        story.append(
            Paragraph(
                f"Generated: {datetime.now().strftime('%d %B %Y, %H:%M')} UTC  •  Role: {role.capitalize()}  •  AI-Powered Analysis",
                s["cover_subtitle"],
            )
        )
        story.append(HRFlowable(width="100%", thickness=2, color=TEAL, spaceAfter=12))

        # ── Executive Summary ──────────────────────────────────────────────
        story.append(Paragraph("EXECUTIVE SUMMARY", s["section_heading"]))
        story.append(Paragraph(f"<b>Business Question:</b> {user_question}", s["body"]))
        story.append(Spacer(1, 4))

        # Headline callout box
        summary_data = [[Paragraph(f"KEY FINDING  |  {headline}", s["highlight_box"])]]
        summary_table = Table(summary_data, colWidths=[doc.width])
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#E8F4FD")),
            ("BOX", (0, 0), (-1, -1), 1.5, TEAL),
            ("LEFTPADDING", (0, 0), (-1, -1), 14),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 10))

        # ── Analysis section ───────────────────────────────────────────────
        story.append(Paragraph("ANALYTICAL FINDINGS", s["section_heading"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY, spaceAfter=6))

        for para in analysis.split("\n"):
            para = para.strip()
            if not para:
                story.append(Spacer(1, 4))
            elif para.startswith(("**", "##", "KEY ", "PATTERN", "ANOMAL", "FINDING", "RISK")):
                story.append(Paragraph(para.replace("**", "").replace("##", "").strip(), s["section_heading"]))
            else:
                story.append(Paragraph(para, s["body"]))

        # ── Data Table ─────────────────────────────────────────────────────
        if df is not None and not df.empty:
            story.append(PageBreak())
            story.append(Paragraph("DATA SNAPSHOT", s["section_heading"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY, spaceAfter=6))
            story.append(
                Paragraph(
                    f"Showing top {min(20, len(df))} of {len(df)} rows returned by the query.",
                    s["small_label"],
                )
            )
            story.append(Spacer(1, 6))
            story.append(self._df_to_table(df, max_rows=20))

            # Descriptive statistics
            numeric_df = df.select_dtypes(include=[np.number])
            if not numeric_df.empty:
                story.append(Spacer(1, 12))
                story.append(Paragraph("DESCRIPTIVE STATISTICS", s["section_heading"]))
                stats_df = numeric_df.describe().round(2).reset_index()
                story.append(self._df_to_table(stats_df, max_rows=10))

        # ── Anomalies section ──────────────────────────────────────────────
        if anomalies:
            story.append(Spacer(1, 10))
            story.append(Paragraph("ANOMALIES & ALERTS", s["section_heading"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=ALERT_RED, spaceAfter=6))

            for a in anomalies[:8]:
                severity = getattr(a, "severity", "medium") if hasattr(a, "severity") else a.get("severity", "medium")
                severity_color = {
                    "critical": ALERT_RED,
                    "high": ALERT_AMBER,
                    "medium": colors.HexColor("#F39C12"),
                    "low": ALERT_GREEN,
                }.get(severity, MID_GRAY)

                desc = getattr(a, "description", "") if hasattr(a, "description") else a.get("description", "")
                metric = getattr(a, "metric", "") if hasattr(a, "metric") else a.get("metric", "")

                anomaly_data = [[
                    Paragraph(
                        f"<b>[{severity.upper()}]</b>  {metric}",
                        ParagraphStyle("ah", fontName="Helvetica-Bold", fontSize=9, textColor=severity_color),
                    ),
                    Paragraph(desc, s["body"]),
                ]]
                at = Table(anomaly_data, colWidths=[3.5 * cm, doc.width - 3.5 * cm])
                at.setStyle(TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D7E2")),
                    ("ROWBACKGROUNDS", (0, 0), (-1, -1), [LIGHT_GRAY]),
                ]))
                story.append(at)
                story.append(Spacer(1, 4))

        # ── Recommendations ────────────────────────────────────────────────
        story.append(PageBreak())
        story.append(Paragraph("STRATEGIC RECOMMENDATIONS", s["section_heading"]))
        story.append(HRFlowable(width="100%", thickness=2, color=TEAL, spaceAfter=8))

        for para in recommendations.split("\n"):
            para = para.strip()
            if not para:
                story.append(Spacer(1, 4))
            elif para[:2].rstrip(".").isdigit() or para.startswith(("PRIORITY", "STRATEGIC", "IMMEDIATE", "RISK", "WATCH", "TEAM", "COACHING", "30-DAY")):
                story.append(Paragraph(para, s["section_heading"]))
            else:
                story.append(Paragraph(para, s["body"]))

        # ── Technical appendix ─────────────────────────────────────────────
        if sql_query:
            story.append(PageBreak())
            story.append(Paragraph("TECHNICAL APPENDIX", s["section_heading"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_GRAY, spaceAfter=6))
            story.append(Paragraph("SQL Query Used:", s["small_label"]))

            sql_data = [[Paragraph(sql_query, ParagraphStyle(
                "sql",
                fontName="Courier",
                fontSize=8,
                textColor=colors.HexColor("#1E3A5F"),
                leading=12,
                leftIndent=6,
            ))]]
            sql_table = Table(sql_data, colWidths=[doc.width])
            sql_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F0F4F8")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#BDC3C7")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(sql_table)

        # ── Build PDF ──────────────────────────────────────────────────────
        try:
            doc.build(story)
            buffer.seek(0)
            return buffer
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise
